services:
  ytmirror:
    build: .
    container_name: ytmirror
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - chrome-profile:/data/chrome-profile
    shm_size: "256mb"
    env_file:
      - .env

volumes:
  chrome-profile:
