services:
  ytmirror:
    build: .
    container_name: ytmirror
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "5900:5900"
      - "8888:8888"
    volumes:
      - chrome-profile:/data/chrome-profile
    shm_size: "256mb"
    env_file:
      - .env

volumes:
  chrome-profile:
