[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[program:ytmirror]
command=node /app/index.js
directory=/app
autorestart=true
priority=1
environment=PULSE_SERVER="unix:/var/run/pulse/native",APP_PORT="%(ENV_APP_PORT)s"
stdout_logfile=/var/log/supervisor/ytmirror.log
stderr_logfile=/var/log/supervisor/ytmirror.log
